volumes:
  postgres-data:
      external: true
  pg-admin:
    external: true
services:
  postgres:
      build:
          context: ./relational-data
          dockerfile: ./Dockerfile.dev
      volumes:
          - postgres-data:/var/lib/postgresql/data
      environment:
          - POSTGRES_MULTIPLE_DATABASES=breweries_and_beers,users_and_favorites
          - POSTGRES_PASSWORD=test-databases
      ports:
          - 15432:5432

  breweries_and_beers:
    build:
      context: ./breweries_and_beers
      dockerfile: ./Dockerfile.dev
    ports:
      - 8090:8000
    volumes:
      - ./breweries_and_beers:/app
    environment:
      DATABASE_URL: postgresql://breweries_and_beers:password@postgres/breweries_and_beers
      WAIT_HOSTS: postgres:5432 
    
  users_and_favorites:
    build:
        context: ./users_and_favorites
        dockerfile: ./Dockerfile.dev
    ports:
        - 8100:8000
    volumes:
        - ./users_and_favorites:/app
    environment:
      DATABASE_URL: postgresql://users_and_favorites:password@postgres/users_and_favorites
      WAIT_HOSTS: postgres:5432 
      
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000
      
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: username@hackreactor.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
            