# volumes:
services:
  breweries_and_beers:
    build:
      context: ./breweries_and_beers
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./breweries_and_beers:/app
    
  users_and_favorites:
    build:
        context: ./users_and_favorites
        dockerfile: ./Dockerfile.dev
    ports:
        - 8001:8001
    volumes:
        - ./users_and_favorites:/app
    environment:
  
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000

            